**代码演示部分：配合本章学习材料使用**  
**第一部分：张量运算示例**  
这里将演示Tensor的一些基本操作

In [1]:
import torch

In [3]:
?torch.tensor

Docstring:
tensor(data, *, dtype=None, device=None, requires_grad=False, pin_memory=False) -> Tensor

Constructs a tensor with no autograd history (also known as a "leaf tensor", see :doc:`/notes/autograd`) by copying :attr:`data`.

.. warning::

    When working with tensors prefer using :func:`torch.Tensor.clone`,
    :func:`torch.Tensor.detach`, and :func:`torch.Tensor.requires_grad_` for
    readability. Letting `t` be a tensor, ``torch.tensor(t)`` is equivalent to
    ``t.clone().detach()``, and ``torch.tensor(t, requires_grad=True)``
    is equivalent to ``t.clone().detach().requires_grad_(True)``.

.. seealso::

    :func:`torch.as_tensor` preserves autograd history and avoids copies where possible.
    :func:`torch.from_numpy` creates a tensor that shares storage with a NumPy array.

Args:
    data (array_like): Initial data for the tensor. Can be a list, tuple,
        NumPy ``ndarray``, scalar, and other types.

Keyword args:
    dtype (:class:`torch.dtype`, optional): the de

In [4]:
# 创建tensor，用dtype指定类型。注意类型要匹配
a = torch.tensor(1.0, dtype=torch.float)
b = torch.tensor(1, dtype=torch.long)
c = torch.tensor(1.0, dtype=torch.int8)
print(a, b, c)

tensor(1.) tensor(1) tensor(1, dtype=torch.int8)


C:\Users\zk\AppData\Local\Temp\ipykernel_12060\512902504.py:4: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  c = torch.tensor(1.0, dtype=torch.int8)


In [6]:
x = torch.tensor([5.5, 3]) 
x

tensor([5.5000, 3.0000])

In [9]:
x = x.new_ones(4, 3, dtype=torch.double) 
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [35]:
#返回同样形状的张量，每个元素都是从均值为0、方差为1的标准正态分布中随机采样得到
x = torch.randn_like(x, dtype=torch.float)
x

tensor([[ 0.9631, -1.2488, -0.1428],
        [-0.7752,  0.2844,  0.5342],
        [ 0.8606, -0.4261, -0.4268],
        [-1.3713, -1.9277, -0.6909]])

In [36]:
#随机，torch.FloatTensor，torch.DoubleTensor，torch.LongTensor
torch.Tensor(2,3)

tensor([[8.3891e-07, 6.5989e-10, 1.3517e+22],
        [3.3356e-09, 5.3366e-08, 8.3815e-10]])

In [37]:
#对角为1，其余为0
torch.eye(3,3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [38]:
#从2到10，步长为2
torch.arange(2,10,2)

tensor([2, 4, 6, 8])

In [39]:
#从2到10，均匀分成6份
torch.linspace(2,10,6)

tensor([ 2.0000,  3.6000,  5.2000,  6.8000,  8.4000, 10.0000])

In [40]:
#正态分布(均值为0，标准差是1，(10,2)为张量形状)
torch.normal(0,1,(10,2))

tensor([[ 0.4099, -1.1145],
        [-2.4499, -0.2920],
        [-1.1956,  1.0149],
        [-1.2209, -0.2915],
        [ 0.1246, -0.2987],
        [ 1.5374, -0.7195],
        [ 0.0730,  0.4176],
        [ 0.6964, -0.9562],
        [ 1.2394, -1.0598],
        [-0.2145, -0.4991]])

In [41]:
#0-5随机排列
torch.randperm(5)

tensor([1, 4, 3, 0, 2])

In [50]:
#item将一个张量转换成标量
x = torch.randn(1) 
print(x)
print(x.item())

tensor([1.2597])
1.2597254514694214


In [4]:
# 使用指定类型函数随机初始化指定大小的tensor
d = torch.FloatTensor(2,3)
e = torch.IntTensor(2)
f = torch.IntTensor([1,2,3,4])  #对于python已经定义好的数据结构可以直接转换
print(d, '\n', e, '\n', f)

tensor([[ 7.2398e-07,  4.5710e-41, -2.0912e+23],
        [ 3.0812e-41,  6.7262e-43,  0.0000e+00]]) 
 tensor([64,  0], dtype=torch.int32) 
 tensor([1, 2, 3, 4], dtype=torch.int32)


In [6]:
# tensor和numpy array之间的相互转换
import numpy as np

g = np.array([[1,2,3],[4,5,6]])
h = torch.tensor(g)
print(h)
i = torch.from_numpy(g)
print(i)
j = h.numpy()
print(j)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])
[[1 2 3]
 [4 5 6]]


注意：torch.tensor创建得到的张量和原数据是不共享内存的，张量对应的变量是独立变量。  
而torch.from_numpy()和torch.as_tensor()从numpy array创建得到的张量和原数据是共享内存的，张量对应的变量不是独立变量，修改numpy array会导致对应tensor的改变。

In [ ]:
g[0,0] = 100
print(i)

In [10]:
# 常见的构造Tensor的函数
k = torch.rand(2, 3) 
l = torch.ones(2, 3)
m = torch.zeros(2, 3)
n = torch.arange(0, 10, 2)
print(k, '\n', l, '\n', m, '\n', n)

tensor([[0.2652, 0.0650, 0.5593],
        [0.7864, 0.0015, 0.4458]]) 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 
 tensor([0, 2, 4, 6, 8])


In [11]:
# 查看tensor的维度信息（两种方式）
print(k.shape)
print(k.size())

torch.Size([2, 3])
torch.Size([2, 3])


In [12]:
# tensor的运算
o = torch.add(k,l)
print(o)

tensor([[1.2652, 1.0650, 1.5593],
        [1.7864, 1.0015, 1.4458]])


In [13]:
# tensor的索引方式与numpy类似
print(o[:,1])
print(o[0,:])

tensor([1.0650, 1.0015])
tensor([1.2652, 1.0650, 1.5593])


In [16]:
# 改变tensor形状的神器：view
print(o.view((3,2)))
print(o.view(-1,2))

tensor([[1.2652, 1.0650],
        [1.5593, 1.7864],
        [1.0015, 1.4458]])
tensor([[1.2652, 1.0650],
        [1.5593, 1.7864],
        [1.0015, 1.4458]])


In [17]:
# tensor的广播机制（使用时要注意这个特性）
p = torch.arange(1, 3).view(1, 2)
print(p)
q = torch.arange(1, 4).view(3, 1)
print(q)
print(p + q)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


In [18]:
# 扩展&压缩tensor的维度：squeeze
print(o)
r = o.unsqueeze(1)
print(r)
print(r.shape)

tensor([[1.2652, 1.0650, 1.5593],
        [1.7864, 1.0015, 1.4458]])
tensor([[[1.2652, 1.0650, 1.5593]],

        [[1.7864, 1.0015, 1.4458]]])
torch.Size([2, 1, 3])


In [19]:
s = r.squeeze(0)
print(s)
print(s.shape)

tensor([[[1.2652, 1.0650, 1.5593]],

        [[1.7864, 1.0015, 1.4458]]])
torch.Size([2, 1, 3])


In [20]:
t = r.squeeze(1)
print(t)
print(t.shape)

tensor([[1.2652, 1.0650, 1.5593],
        [1.7864, 1.0015, 1.4458]])
torch.Size([2, 3])


**第二部分：自动求导示例**  
这里将通过一个简单的函数  $y=x_1+2*x_2$  来说明PyTorch自动求导的过程

In [98]:
x = torch.ones(2, 2, requires_grad=True)
y = x**2
z = y * y * 3
y

tensor([[1., 1.],
        [1., 1.]], grad_fn=<PowBackward0>)

In [99]:
y.backward(torch.tensor([[1,1],[1,1]]))

In [102]:
#x^2 的导数为 2x
print(x)
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[2., 2.],
        [2., 2.]])


In [22]:
import torch

x1 = torch.tensor(1.0, requires_grad=True)
x2 = torch.tensor(2.0, requires_grad=True)
y = x1 + 2*x2
print(y)

tensor(5., grad_fn=<AddBackward0>)


In [23]:
# 首先查看每个变量是否需要求导
print(x1.requires_grad)
print(x2.requires_grad)
print(y.requires_grad)

True
True
True


In [24]:
# 查看每个变量导数大小。此时因为还没有反向传播，因此导数都不存在
print(x1.grad.data)
print(x2.grad.data)
print(y.grad.data)

AttributeError: 'NoneType' object has no attribute 'data'

In [25]:
x1

tensor(1., requires_grad=True)

In [26]:
## 反向传播后看导数大小
y = x1 + 2*x2
y.backward()
print(x1.grad.data)
print(x2.grad.data)

tensor(1.)
tensor(2.)


In [30]:
# 导数是会累积的，重复运行相同命令，grad会增加
y = x1 + 2*x2
y.backward()
print(x1.grad.data)
print(x2.grad.data)

tensor(5.)
tensor(10.)


In [ ]:
# 所以每次计算前需要清除当前导数值避免累积，这一功能可以通过pytorch的optimizer实现。后续会讲到

In [31]:
# 尝试，如果不允许求导，会出现什么情况？
x1 = torch.tensor(1.0, requires_grad=False)
x2 = torch.tensor(2.0, requires_grad=False)
y = x1 + 2*x2
y.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn